config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :supplements do
    collection do
      get 'search'
    end
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/supplement.rb
class Supplement < ApplicationRecord
  belongs_to :user
  attachment :image

  def self.search(search)
    if search != ""
      Supplement.where('title LIKE(?)', "%#{search}%")
    else
      Supplement.all
    end
  end

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :supplements, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/supplements_controller.rb
class SupplementsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @supplements = Supplement.all
  end

  def show
    @supplement = Supplement.find(params[:id])
  end

  def new
    @supplement = Supplement.new
  end

  def create
    @supplement = Supplement.new(supplement_params)
    @supplement.user_id = current_user.id
    if @supplement.save
      redirect_to supplement_path(@supplement), notice: '投稿しました' 
    else
      render :new
    end
  end

  def edit
    @supplement = Supplement.find(params[:id])
    if @supplement.user != current_user
      redirect_to supplements_path, alert: '不正なアクセスです'
    end
  end

  def update
    @supplement = Supplement.find(params[:id])
    if @supplement.update(supplement_params)
      redirect_to supplement_path(@supplement), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    supplement = Supplement.find(params[:id])
    supplement.destroy
    redirect_to user_path(supplement.user), notice: "レシピを削除しました。"
  end

  def search
    @supplements = Supplement.search(params[:keyword])
  end

  private
  def  supplement_params
     params.require(:supplement).permit(:title, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path(current_user), alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '更新しました'
    else
      render :edit
    end
  end 

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/supplements_helper.rb
module SupplementsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">SUPPAPP</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-dark is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-dark is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suppapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-warning">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-warning">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-grey-dark">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-9" style="font-family: cursive;">SUPPAPP</h1>
        <% end %>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "サプリ一覧", supplements_path, class: "navbar-item button is-dark" %>
          </div>
          <div class="navbar-item">
            <%= link_to "新規投稿", new_supplement_path, class: "navbar-item button is-dark" %>
          </div>   
          
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "投稿者一覧", users_path, class: "button is-dark" %>
                </p>
                <p class="control">
                <%= link_to "マイページ", user_path(current_user), class: "button is-dark" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-dark" %>
                </p>
                <p class="control">
                  <%= link_to "検索画面へ", search_supplements_path, method: :get, class: "button is-dark" %>
                </p>
            </div>
           </div>
        </div>
      </div>
    <% else %>
     <div id="navbarExampleTransparentExample" class="navbar-menu">
       <div class="navbar-item">
         <%= link_to "サプリ一覧", supplements_path, class: "navbar-item button is-dark" %>
       </div>
       <div class="navbar-item">
         <%= link_to "投稿者一覧", users_path, class: "navbar-item button is-dark" %>
       </div>
       <div class="navbar-end">
         <div class="navbar-item">
           <div class="field is-grouped">
             <p class="control">
               <%= link_to "ログイン", new_user_session_path, class: "button is-dark" %>
             </p>
             <p class="control">
               <%= link_to "新規登録", new_user_registration_path, class: "button is-dark" %>
             </p>
             <p class="control">
               <%= link_to "検索画面へ", search_supplements_path, method: :get, class: "button is-dark" %>
             </p>
           </div>
         </div>
       </div>
     </div>
    <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/supplements/_supplement.html.erb
<div class="column is-4">
  <div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
        <%= link_to supplement_path(supplement) do %> 
          <%= attachment_image_tag supplement, :image %>
        <% end %>
    </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <%= attachment_image_tag supplement.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
          </figure>
        </div>
        <div class="media-content">
          <div class="title"><%= link_to supplement.user.username, user_path(supplement.user) %></div>
        </div>
      </div>
      <div class="content">
        <time><%= supplement.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
      </div>
    </div>
  </div>
</div>

app/views/supplements/edit.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        サプリ編集
      </h1>
    </div>
  </div>
</section>

<% if @supplement.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@supplement.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @supplement.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @supplement do |f| %>
          <div class="field">
            <%= f.label :title, "サプリ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "サプリ詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "textarea" %>
          </div>

          <%= f.submit '投稿', class: "button is-black"%>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/supplements/index.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        サプリ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @supplements.each do |supplement| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to supplement_path(supplement) do %>
                  <%= attachment_image_tag supplement, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag supplement.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to supplement.user.username, user_path(supplement.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= supplement.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/supplements/new.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規サプリ投稿
      </h1>
    </div>
  </div>
</section>

<% if @supplement.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@supplement.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @supplement.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @supplement do |f| %>
          <div class="field">
            <%= f.label :title, "サプリ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "サプリ詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
    

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-black" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/supplements/search.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        検索一覧
      </h1>
      <%= form_with(url: search_supplements_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
    </div>
  </div>
</section>


<section class="section">
  <div class="contents row">
    <div class="columns is-multiline">
      <% @supplements.each do |supplement| %>
        <%= render partial: "supplement", locals: { supplement: supplement } %>
      <% end %>
    </div>
  </div>
</section>

app/views/supplements/show.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        サプリ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @supplement, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @supplement.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>詳細</th>
                </tr>
                <tr>
                  <td><%= simple_format @supplement.body %></td>
                </tr>
              </table>
              <% if @supplement.user.id == current_user.id %>
                <%= link_to "編集", edit_supplement_path(@supplement), class: "button is-black" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-4">
        <article class="panel is-black">
          <p class="panel-heading">
            <%= @supplement.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @supplement.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@supplement.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @supplement.user.username %>さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6" >
        <%= form_for @user do |f| %>

            <div class="field">
                <%= f.label :username, "ユーザーネーム", class: "label" %>
                <%= f.text_field :username, class: "input" %>
                </div>

            <div class="field">
                <%= f.label :email, "メールアドレス", class: "label" %>
                <%= f.text_field :email, class:"input" %>
            </div>


            <div class="field">
                <%= f.label :profile, "プロフィール", class:"label" %>
                <%= f.text_field :profile, class:"textarea" %>
            </div>

            <div class="field">
                <%= f.label :profile_image, "プロフィール画像", class:"label" %>
                <%= f.attachment_field :profile_image, class:"input" %>
            </div>

            <%= f.submit "更新", class: "button is-dark" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
        <h1 class="title">
          紹介者一覧
        </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns ismultiline">
      <% @users.each do |user| %>
      <div class="column is-3">
        <div class="card">
          <div class="card-content">
            <div class="card-image">
              <figure class="image">
                <%= link_to user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <div class="title"><%=link_to user.username, user_path(user) %></div>
            </div>
             </div>
            <div class="content">
              投稿数 :<%= user.supplements.count %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
   </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-black">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-dark" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.supplements.each do |supplement| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= attachment_image_tag supplement, :image %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to supplement_path(supplement), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このサプリを見る
                  <% end %>
                  <% if @user.id == current_user.id  %>
                  <%= link_to edit_supplement_path(supplement), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-edit"></i>
                    </span>
                    このサプリ内容を編集する
                  <% end %>
                  <%= link_to supplement_path(supplement), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-trash"></i>
                    </span>
                    このレシピを削除する
                  <% end %>
                 <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= supplement.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>